# Generated by Django 4.0.8 on 2022-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_update_human_pages_human_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='human',
            name='pages',
        ),
        migrations.AddField(
            model_name='human',
            name='webpage_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='human',
            name='webpages',
            field=models.ManyToManyField(to='humans.webpage'),
        ),
    ]
