# Generated by Django 4.0.8 on 2022-11-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_webpage_remove_human_pages_human_webpage_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='webpages',
            new_name='found_on',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='webpage_log',
            new_name='found_on_log',
        ),
    ]
