# Generated by Django 4.0.8 on 2022-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_rename_webpages_human_found_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='id',
        ),
        migrations.AlterField(
            model_name='human',
            name='found_on',
            field=models.ManyToManyField(blank=True, to='humans.webpage'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
