# Generated by Django 4.0.8 on 2022-11-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0006_remove_update_id_alter_human_found_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='updates',
        ),
    ]
