# Generated by Django 4.0.8 on 2022-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0007_remove_human_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='updates',
            field=models.ManyToManyField(to='humans.update'),
        ),
    ]
