# Generated by Django 4.0.8 on 2022-11-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0008_human_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='found_on',
        ),
        migrations.RemoveField(
            model_name='human',
            name='found_on_log',
        ),
        migrations.RemoveField(
            model_name='human',
            name='updates',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
