# Generated by Django 4.0.8 on 2022-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0009_remove_human_found_on_remove_human_found_on_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.SlugField(max_length=200)),
            ],
            options={
                'unique_together': {('date', 'source')},
            },
        ),
        migrations.AddField(
            model_name='human',
            name='updates',
            field=models.ManyToManyField(to='humans.update'),
        ),
    ]
