# Generated by Django 4.0.8 on 2022-11-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0010_update_human_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikidata',
            old_name='qid',
            new_name='human',
        ),
        migrations.RenameField(
            model_name='wikipedia',
            old_name='qid',
            new_name='human',
        ),
    ]
