# Generated by Django 4.0.8 on 2022-11-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0011_rename_qid_wikidata_human_rename_qid_wikipedia_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidata',
            name='wikipedia',
        ),
        migrations.DeleteModel(
            name='Wikipedia',
        ),
    ]
