# Generated by Django 4.0.8 on 2022-11-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0012_remove_wikidata_wikipedia_delete_wikipedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enwikititle', models.SlugField(blank=True, max_length=200, null=True)),
                ('pagesize', models.PositiveIntegerField(blank=True, null=True)),
                ('recentviews', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('f', 'Featured'), ('g', 'Good'), ('u', 'Ungraded')], max_length=1)),
                ('editcount', models.PositiveIntegerField(blank=True, null=True)),
                ('recentedits', models.PositiveIntegerField(blank=True, null=True)),
                ('connections', models.ManyToManyField(to='humans.wikipedia')),
            ],
        ),
        migrations.AddField(
            model_name='wikidata',
            name='wikipedia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.wikipedia'),
        ),
    ]
