# Generated by Django 4.0.8 on 2022-11-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0013_wikipedia_wikidata_wikipedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipedia',
            old_name='enwikititle',
            new_name='title',
        ),
    ]
