# Generated by Django 4.0.8 on 2022-11-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0014_rename_enwikititle_wikipedia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidata',
            name='wikipedia',
        ),
        migrations.DeleteModel(
            name='Wikipedia',
        ),
    ]
